apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
  namespace: jivas
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo
          command:
            - sh
            - -c
            - |
              sleep 10
              until mongosh --host mongodb-0.mongodb-headless.jivas.svc.cluster.local --eval "print(1)"; do sleep 5; done
              mongosh --host mongodb-0.mongodb-headless.jivas.svc.cluster.local <<EOF
              rs.initiate({
                _id: 'rs0',
                members: [
                  { _id : 0, host : "mongodb-0.mongodb-headless.jivas.svc.cluster.local:27017" },
                  { _id : 1, host : "mongodb-1.mongodb-headless.jivas.svc.cluster.local:27017" },
                ]
              })
              EOF
      restartPolicy: OnFailure
